# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
version: '3.7'
services:
  ha:
    image: homeassistant/home-assistant:stable
    container_name: test_ha
    ports:
      - 9999:8123
    environment:
      - TZ=America/Panama
      - SECRET=the_secret
    volumes:
      - ./ha_config:/config

